### ISSUE TITLE
Mention and compare to existing alternatives in readme?

### ISSUE THREAD

**Issue by hartwork** [weddige/django-hibp#1]
Hi @weddige, nice project! :+1: 

I think it would be nice to add a quick comparison to existing alternatives to the readme. What I found using a quick search was these three:

- https://github.com/guhan94/django-hibp-validator (not in PyPI)
- https://github.com/tombiasz/django-hibpwned (archived repository, not in PyPI)
- https://github.com/lionheart/django-pwnedpasswords-validator (in PyPI, latest release of 2018, latest Git commit of 2019)

So the first two are non-options, the third would be interesting to have a comparison to.

Just an idea, no hard feelings if there is no interest in adding notes like that.

Best, Sebastian

**Comment by weddige** [comment]
Thanks for raising the issue. I gave it some thought and decided not to do it. I don't want to create any artificial competition between implementations that are essentially quite similar, or exaggerate the importance of my design choices (basically to use only the standard Python library and keep the 29 lines of code in one file).

But I have improved the README to include these design choices in order to have some unique selling points for this library.

**Comment by hartwork** [comment]
@weddige thanks for your consideration. The code can be understood and reviewed in 5 minutes, I think your design choices are great for security :+1: The only current minor downside I can think of is performance (compared to having a full local copy of the database or a [bloom filter](https://github.com/hannob/pwbloom) to compare to) but that's "only" performance and comes with additional complexity…

Have a nice day :beers: 

PS: Note to self, related commit is 92a881ee29ec20cc7c2e483fda075ec3f503c9c9

**Comment by weddige** [comment]
Performance, and even more availability, is an issue with this approach. However, having the entire HIBP database available offline (and even updated) is not a viable option in almost all use cases IMHO.

I have written an article about my thoughts on how to get the best of both worlds. Maybe you'll find it of interest: https://lutrasecurity.com/en/articles/django-password-validation/

**Comment by hartwork** [comment]
Hi @weddige thanks for the link. I'm unsure what the "the best of both worlds" in the article is:
- is it the `fail_on_error = False` for availability?
- is it the use of a smaller local `common-passwords-lower.txt.gz`?

What I'd do probably depends on how serious the application is. I think would consider having a daemon that periodically asks the API for the 16^5 hash ranges similar to the official https://github.com/HaveIBeenPwned/PwnedPasswordsDownloader and either use that (a) for direct file I/O, (b) a clone of the API that sits in my local network with controlled availability and round trip time, or (c) generate a small bloom filter for download and sync that file every few days. Out of those, I think the bloom filter could even be extended on the fly so that it would not need gigabytes of space, not even temporarily. Otherwise disk space may be a key factor.
It would probably not be hard to offer as a service to the community, but the question is what the community would trust that the deployed services does what it advertises, when the resulting bloom filter would be expensive to validate, it would be harder to trust than the raw SHA1s than bloom assembled yourself. Maybe it's a different store if all work runs in a public GitHub Actions CI and the changes to the filter over time are fully transparent in Git.

Two small notes about language in the article:
- There are multiple occurrences of "Djangos" in there where I would expect `Django's` with an apostrophe.
- The use of `20 000` with spaces rather than comma a la `20,000` reads rather weird to me, first time I see that as a pattern.

Just my two cents.

CC @hannob

**Comment by hartwork** [comment]
PS: If my math is correct, storing SHA1s and their frequencies for 1 billion collision-free passwords would take about 50 GiB space on disk:

```
In [3]: 1_000_000_000 * 50 / (2 ** 30)
Out[3]: 46.566128730773926
```

**Comment by hartwork** [comment]
PS: I've hacked together https://gist.github.com/hartwork/4ba09a83e66c0f5e7937e7351fe0039d now for something that I can use with ease on the terminal. (I needed something that doesn't move relative to me after review.)

**Comment by weddige** [comment]
> Hi @weddige thanks for the link. I'm unsure what the "the best of both worlds" in the article is:

The aim was to be able to check against the full HIBP dataset, but still have a reasonable offline check. I expect most applications to be able to handle 20k passwords. Once we get into a few MBs or even GBs, the security return for most applications will diminish.

However, with limited size, breach corpuses are not an ideal data source to check against, as they are merely a heuristic for the password lists that will be used in the attacks, and will get worse if only a subset is used. By using a password list collected from honeypots, the offline check becomes not only a fallback, but also an extension of the check against HIBP (last time I checked, between 10-20% of login attempts are not in HIBP).

These considerations can change, and the use of larger offline datasets might become feasible for applications with higher security requirements. But at that point, password policies are not the way to go anyway.

Regarding your comments on the article: 

 * Djangos somehow slipped through the proofreading. Thanks!
 * I prefer the space because I've seen too much confusion about the decimal separator and don't want to add the thousands separator to the mix. A thin space would probably be a better solution, but that's too annoying to type.

Thanks for the discussion :-)

**Comment by hartwork** [comment]
Hi @weddige,

> last time I checked, between 10-20% of login attempts are not in HIBP

with some luck, that's something that could potentially be fixed easily: I could imagine Troy would be happy to add your honeypot dataset and then HIBP would have again what you need. Could probably even work in a way that is marketable. Jst an idea.

> Thanks for the discussion :-)

Likewise! :beers:
